
"""
The Pages branch holds one directory per report format::

    <pages-dir>/reports/<kind>/<label>/   pytest-html, one self-contained file
    <pages-dir>/allure/<kind>/<label>/    Allure, generated by the Allure CLI

Each run directory holds an ``index.html`` and a ``status.txt``. This script
scans both trees and writes a bento-grid page with a section per format,
newest run first. Either format may be absent; empty sections are skipped.

Whichever workflow publishes last rebuilds the page, so the scan is
deliberately stateless — it reports whatever is on the branch right now.

"""

from __future__ import annotations

import argparse
import html
import os
from pathlib import Path

STATUS_CLASS = {"success": "ok", "failure": "fail"}
STATUS_LABEL = {"success": "passed", "failure": "failed"}

# (directory, heading, blurb) — the order here is the order on the page.
SECTIONS = (
    (
        "reports",
        "pytest-html",
        "One self-contained HTML file per run, themed with a custom stylesheet.",
    ),
    (
        "allure",
        "Allure",
        "Steps, attachments and trends across runs, built by the Allure CLI.",
    ),
)


def collect_runs(reports_dir: Path) -> list[tuple[str, str, str]]:
    """Return (kind, label, status) for every published run, newest first."""
    runs: list[tuple[str, str, str]] = []
    if not reports_dir.is_dir():
        return runs

    for kind_dir in sorted(reports_dir.iterdir()):
        if not kind_dir.is_dir():
            continue
        for entry in kind_dir.iterdir():
            if not entry.is_dir():
                continue
            status_file = entry / "status.txt"
            status = "unknown"
            if status_file.exists():
                status = status_file.read_text(encoding="utf-8").strip() or "unknown"
            runs.append((kind_dir.name, entry.name, status))

    # Labels start with an ISO date, so a plain string sort is chronological.
    runs.sort(key=lambda run: run[1], reverse=True)
    return runs


def split_label(label: str) -> tuple[str, str, str]:
    """'2026-08-02_14-30-run57' -> ('2026-08-02', '14:30', '57')."""
    head, _, run = label.partition("-run")
    date, _, hhmm = head.partition("_")
    return date, hhmm.replace("-", ":"), run


def status_class(status: str) -> str:
    return STATUS_CLASS.get(status, "unknown")


def status_label(status: str) -> str:
    return STATUS_LABEL.get(status, status)


def render_card(root: str, kind: str, label: str, status: str, *, featured: bool) -> str:
    date, time, run = split_label(label)
    meta = " · ".join(part for part in (time, f"run {run}" if run else "") if part)
    classes = "tile card card--featured" if featured else "tile card"
    pin = '<span class="pin">latest</span>' if featured else ""
    return (
        f'<a class="{classes}" href="{html.escape(root)}/{html.escape(kind)}/{html.escape(label)}/index.html">'
        f'<div class="card__top"><span class="tag tag--{html.escape(kind)}">{html.escape(kind)}</span>{pin}</div>'
        f'<div class="card__date">{html.escape(date)}</div>'
        f'<div class="card__meta">{html.escape(meta)}</div>'
        f'<div class="card__status s--{status_class(status)}">'
        f'<i class="dot"></i>{html.escape(status_label(status))}</div>'
        "</a>"
    )


def render_hero(title: str, runs: list[tuple[str, str, str]]) -> str:
    if runs:
        kind, label, status = runs[0]
        date, time, _ = split_label(label)
        state = (
            f'<div class="hero__state s--{status_class(status)}"><i class="dot"></i>'
            f"{html.escape(kind)} · {html.escape(status_label(status))}</div>"
            f'<div class="hero__when">{html.escape(date)}{" " + html.escape(time) if time else ""}</div>'
        )
        sub = "Every published run, newest first. Open a tile for the full HTML report."
    else:
        state = (
            '<div class="hero__state s--unknown"><i class="dot"></i>no runs yet</div>'
            '<div class="hero__when">Reports appear here after the first workflow run.</div>'
        )
        sub = "Nothing published yet."

    return (
        '<section class="tile hero">'
        f"<div><h1>{html.escape(title)}</h1>"
        f'<p class="sub">{sub}</p></div>'
        f"{state}</section>"
    )


def render_section(root: str, heading: str, blurb: str, runs) -> str:
    """One titled block with its own grid of run cards. Empty -> nothing."""
    if not runs:
        return ""
    cards = "\n".join(
        render_card(root, kind, label, status, featured=(index == 0))
        for index, (kind, label, status) in enumerate(runs)
    )
    return (
        '<section class="section">'
        f'<div class="section__head"><h2>{html.escape(heading)}</h2>'
        f'<p>{html.escape(blurb)}</p></div>'
        f'<div class="bento">\n{cards}\n</div>'
        "</section>"
    )


def render_page(title: str, sections, css: str) -> str:
    """`sections` is a list of (root, heading, blurb, runs)."""
    # The same run is published under both formats, so count distinct labels
    # rather than directories or the totals double.
    by_label: dict[str, tuple[str, str]] = {}
    for _, _, _, runs in sections:
        for kind, label, status in runs:
            by_label.setdefault(label, (kind, status))

    total = len(by_label)
    passed = sum(1 for kind, status in by_label.values() if status == "success")
    failed = sum(1 for kind, status in by_label.values() if status == "failure")
    nightly = sum(1 for kind, status in by_label.values() if kind == "regression")

    stats = "".join(
        f'<div class="{" ".join(filter(None, ("tile", "stat", modifier)))}">'
        f'<div class="stat__num">{value}</div>'
        f'<div class="stat__key">{key}</div></div>'
        for value, key, modifier in (
            (total, "runs", ""),
            (passed, "passed", "stat--pass"),
            (failed, "failed", "stat--fail"),
            (nightly, "regression", ""),
        )
    )

    newest = [run for _, _, _, runs in sections for run in runs]
    newest.sort(key=lambda run: run[1], reverse=True)

    body = "\n".join(
        block for block in
        (render_section(root, heading, blurb, runs) for root, heading, blurb, runs in sections)
        if block
    )
    if not body:
        body = (
            '<div class="bento"><div class="tile empty">Nothing published yet. '
            "Trigger the UI Tests workflow to generate the first report.</div></div>"
        )

    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{html.escape(title)}</title>\n"
        f"<style>\n{css}\n</style>\n"
        "</head>\n<body>\n"
        '<div class="wrap">\n<div class="bento">\n'
        f"{render_hero(title, newest)}\n{stats}\n</div>\n{body}\n"
        "</div>\n</body>\n</html>\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pages-dir", type=Path, default=Path("gh-pages"))
    parser.add_argument("--output", type=Path, default=None)
    # Defaults to the stylesheet sitting next to this script, so the working
    # directory does not matter.
    parser.add_argument("--css", type=Path, default=Path(__file__).with_name("index.css"))
    parser.add_argument("--title", default="OrangeHRM Autotest Reports")
    args = parser.parse_args()

    if not args.css.is_file():
        raise SystemExit(f"Stylesheet not found: {args.css}")

    sections = [
        (root, heading, blurb, collect_runs(args.pages_dir / root))
        for root, heading, blurb in SECTIONS
    ]
    page = render_page(args.title, sections, args.css.read_text(encoding="utf-8"))

    output = args.output or args.pages_dir / "index.html"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(page, encoding="utf-8")
    listed = ", ".join(f"{heading}: {len(runs)}" for _, heading, _, runs in sections)
    print(f"Wrote {output} — {listed}")


if __name__ == "__main__":
    main()