
# Exists for local setup to be working.
# DO NOT add such config files to CI on real projects code

base_url: "https://opensource-demo.orangehrmlive.com"
credentials:
  username: "Admin"
  password: "admin123"
